---
- name: Убедиться, что директория проекта доступна
  file:
    path: "{{ playbook_dir }}"
    state: directory

# airflow/
- name: Создать директорию airflow
  file:
    path: "{{ playbook_dir }}/airflow"
    state: directory

- name: Копировать Dockerfile для airflow
  copy:
    src: Dockerfile-airflow
    dest: "{{ playbook_dir }}/airflow/Dockerfile"
    mode: '0644'

- name: Копировать requirements.txt
  copy:
    src: requirements.txt
    dest: "{{ playbook_dir }}/airflow/requirements.txt"
    mode: '0644'

# spark/
- name: Создать директорию spark
  file:
    path: "{{ playbook_dir }}/spark"
    state: directory

- name: Копировать spark-defaults.conf
  copy:
    src: spark-defaults.conf
    dest: "{{ playbook_dir }}/spark/spark-defaults.conf"
    mode: '0644'

# monitoring/
- name: Создать директорию monitoring
  file:
    path: "{{ playbook_dir }}/monitoring"
    state: directory

- name: Копировать prometheus.yml
  copy:
    src: prometheus.yml
    dest: "{{ playbook_dir }}/monitoring/prometheus.yml"
    mode: '0644'

# monitoring/airflow-exporter/
- name: Создать директорию monitoring/airflow-exporter
  file:
    path: "{{ playbook_dir }}/monitoring/airflow-exporter"
    state: directory

- name: Копировать Dockerfile для airflow-exporter
  copy:
    src: Dockerfile-exporter
    dest: "{{ playbook_dir }}/monitoring/airflow-exporter/Dockerfile"
    mode: '0644'

# docker-compose.yml
- name: Копировать docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "{{ playbook_dir }}/docker-compose.yml"
    mode: '0644'

# Запуск docker compose
- name: Запустить Docker Compose build
  command: docker compose build
  args:
    chdir: "{{ playbook_dir }}"

- name: Запустить docker compose up -d
  command: docker compose up -d
  args:
    chdir: "{{ playbook_dir }}"
