global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'airflow-exporter'
    static_configs:
      - targets: ['airflow-exporter:9112']

  - job_name: 'spark'
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'spark-master:8080'
        - 'spark-worker:8081'
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
